name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
jobs:
    linux:
        if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
    matrix:
    compiler:
        - gcc
        - clang
    container:
        - suse-qt512
        - suse-qt514
        - suse-qt515
    runs-on: ubuntu-latest
    container: debian:${{ matrix.distro }}
    steps:
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: |
          if [ -n "${{ github.base_ref }}" ]; then
            echo "##[set-output name=branch;]${{ github.base_ref }}"
          else
            github_ref=${{ github.ref }}
            echo "##[set-output name=branch;]${github_ref##*/}"
          fi
      - name: Qt version identifier
        id: qt_version
        shell: bash
        run: |
          qtverid=`echo "${{ matrix.container }}" | sed -e 's,suse-qt,,g'`
          echo "##[set-output name=id;]${qtverid}"
      - name: Build
        run: |
          set -x
          mkdir -p build
          cd build
          # OpenSuSE containers don't have any documentation
          if [ "${{ matrix.compiler }}" == "clang" ]; then
            export CC=clang
            export CXX=clang++
            cmake .. -DLIRI_ENABLE_CLAZY:BOOL=ON -DCMAKE_INSTALL_PREFIX=/usr -DFLUID_WITH_DOCUMENTATION:BOOL=OFF
          else
            cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DFLUID_WITH_DOCUMENTATION:BOOL=OFF
          fi
          make -j $(getconf _NPROCESSORS_ONLN)
          sudo make install
